<h2><center>HOME WORK - 2 </center></h2>
<h3>Team Members:</h3> <br>
Uma Sai Madhuri Jetty<br>
Chaitanya Darade

#### Importing the required libraries and loading the data

In [1]:
from sklearn import linear_model
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import RidgeCV
from sklearn.linear_model import LassoCV
from sklearn.metrics import mean_squared_error, r2_score
import warnings
warnings.filterwarnings("ignore") # to not display any warnings generated 

df_train = pd.read_csv("dodgers_training.csv")
df_test = pd.read_csv("dodgers_testing.csv")

In [2]:
df_train.head()

Unnamed: 0 month  day  attend day_of_week opponent  temp   skies day_night  \
0          58   AUG   20   36878      Monday   Giants    80  Clear      Night   
1          62   AUG   25   40284    Saturday  Marlins    70  Clear      Night   
2          56   AUG    7   55024     Tuesday  Rockies    80  Clear      Night   
3           6   APR   23   26376      Monday   Braves    60  Cloudy     Night   
4          57   AUG    8   37084   Wednesday  Rockies    84  Clear      Night   

  cap shirt fireworks bobblehead  
0  NO    NO        NO         NO  
1  NO    NO        NO         NO  
2  NO    NO        NO        YES  
3  NO    NO        NO         NO  
4  NO    NO        NO         NO

In [3]:
df_test.head()

Unnamed: 0 month  day  attend day_of_week   opponent  temp   skies  \
0          60   AUG   22   40173   Wednesday     Giants    75  Clear    
1          34   JUN   16   45210    Saturday  White Sox    68  Clear    
2          55   AUG    6   32659      Monday    Rockies    79  Clear    
3          31   JUN   12   55279     Tuesday     Angels    66  Cloudy   
4          39   JUL    1   55359      Sunday       Mets    75  Clear    

  day_night cap shirt fireworks bobblehead  
0     Night  NO    NO        NO         NO  
1     Night  NO    NO        NO         NO  
2     Night  NO    NO        NO         NO  
3     Night  NO    NO        NO        YES  
4     Night  NO    NO        NO        YES

### 1) Encoding categorical Attributes

###       a) To select columns which are needed and splitting dependent(y) and independent variables(x)

In [4]:
df_train = df_train[['attend','temp','day_of_week','month','skies','bobblehead']]
df_test = df_test[['attend','temp','day_of_week','month','skies','bobblehead']]

In [5]:
x_df_train = df_train[['temp','day_of_week','month','skies','bobblehead']].copy()
y_df_train= df_train[['attend']].copy()
x_df_test = df_test[['temp','day_of_week','month','skies','bobblehead']].copy()
y_df_test= df_test[['attend']].copy()

### b) One hot encoding

In [6]:
x_df_train = pd.get_dummies(x_df_train)
x_df_test = pd.get_dummies(x_df_test)
print(x_df_train.head())

   temp  day_of_week_Friday  day_of_week_Monday  day_of_week_Saturday  \
0    80                   0                   1                     0   
1    70                   0                   0                     1   
2    80                   0                   0                     0   
3    60                   0                   1                     0   
4    84                   0                   0                     0   

   day_of_week_Sunday  day_of_week_Thursday  day_of_week_Tuesday  \
0                   0                     0                    0   
1                   0                     0                    0   
2                   0                     0                    1   
3                   0                     0                    0   
4                   0                     0                    0   

   day_of_week_Wednesday  month_APR  month_AUG  month_JUL  month_JUN  \
0                      0          0          1          0          0   
1       

## Q1- List the means and standard deviations of the encoded attributes before scaling

In [7]:
print('Means:', x_df_train.mean())
print('Standard Deviations:', x_df_train.std())
print('Means:', x_df_test.mean())
print('Standard Deviations:', x_df_test.std())

Means: temp                     73.642857
day_of_week_Friday        0.178571
day_of_week_Monday        0.142857
day_of_week_Saturday      0.160714
day_of_week_Sunday        0.196429
day_of_week_Thursday      0.089286
day_of_week_Tuesday       0.089286
day_of_week_Wednesday     0.142857
month_APR                 0.160714
month_AUG                 0.214286
month_JUL                 0.089286
month_JUN                 0.089286
month_MAY                 0.232143
month_OCT                 0.017857
month_SEP                 0.196429
skies_Clear               0.803571
skies_Cloudy              0.196429
bobblehead_NO             0.910714
bobblehead_YES            0.089286
dtype: float64
Standard Deviations: temp                     8.949207
day_of_week_Friday       0.386459
day_of_week_Monday       0.353094
day_of_week_Saturday     0.370591
day_of_week_Sunday       0.400892
day_of_week_Thursday     0.287736
day_of_week_Tuesday      0.287736
day_of_week_Wednesday    0.353094
month_APR           

### 2) To ensure same attributes in training and testing dataset, we have added thursday in testing dataset

In [8]:
# To make the number of attributes in testing and training data equal
x_df_test.insert(5, 'day_of_week_Thursday', 0)
x_df_train.info()
x_df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 19 columns):
temp                     56 non-null int64
day_of_week_Friday       56 non-null uint8
day_of_week_Monday       56 non-null uint8
day_of_week_Saturday     56 non-null uint8
day_of_week_Sunday       56 non-null uint8
day_of_week_Thursday     56 non-null uint8
day_of_week_Tuesday      56 non-null uint8
day_of_week_Wednesday    56 non-null uint8
month_APR                56 non-null uint8
month_AUG                56 non-null uint8
month_JUL                56 non-null uint8
month_JUN                56 non-null uint8
month_MAY                56 non-null uint8
month_OCT                56 non-null uint8
month_SEP                56 non-null uint8
skies_Clear              56 non-null uint8
skies_Cloudy             56 non-null uint8
bobblehead_NO            56 non-null uint8
bobblehead_YES           56 non-null uint8
dtypes: int64(1), uint8(18)
memory usage: 1.5 KB
<class 'pandas.core.frame.DataF

### 3) Standardization

In [9]:
# with train data
scaler = preprocessing.StandardScaler(copy=True, with_mean=True, with_std=True)
scaled_x_df_train = scaler.fit_transform(x_df_train)
scaled_x_df_train = pd.DataFrame(scaled_x_df_train, columns=x_df_train.columns)

In [10]:
scaled_x_df_train.head()

temp  day_of_week_Friday  day_of_week_Monday  day_of_week_Saturday  \
0  0.716787           -0.466252            2.449490             -0.437595   
1 -0.410743           -0.466252           -0.408248              2.285218   
2  0.716787           -0.466252           -0.408248             -0.437595   
3 -1.538273           -0.466252            2.449490             -0.437595   
4  1.167799           -0.466252           -0.408248             -0.437595   

   day_of_week_Sunday  day_of_week_Thursday  day_of_week_Tuesday  \
0           -0.494413             -0.313112            -0.313112   
1           -0.494413             -0.313112            -0.313112   
2           -0.494413             -0.313112             3.193744   
3           -0.494413             -0.313112            -0.313112   
4           -0.494413             -0.313112            -0.313112   

   day_of_week_Wednesday  month_APR  month_AUG  month_JUL  month_JUN  \
0              -0.408248  -0.437595   1.914854  -0.313112  -0.313112   
1              -0.408248  -0.437595   1.914854  -0.313112  -0.313112   
2              -0.408248  -0.437595   1.914854  -0.313112  -0.313112   
3              -0.408248   2.285218  -0.522233  -0.313112  -0.313112   
4               2.449490  -0.437595   1.914854  -0.313112  -0.313112   

   month_MAY  month_OCT  month_SEP  skies_Clear   skies_Cloudy  bobblehead_NO  \
0  -0.549841   -0.13484  -0.494413      0.494413     -0.494413       0.313112   
1  -0.549841   -0.13484  -0.494413      0.494413     -0.494413       0.313112   
2  -0.549841   -0.13484  -0.494413      0.494413     -0.494413      -3.193744   
3  -0.549841   -0.13484  -0.494413     -2.022600      2.022600       0.313112   
4  -0.549841   -0.13484  -0.494413      0.494413     -0.494413       0.313112   

   bobblehead_YES  
0       -0.313112  
1       -0.313112  
2        3.193744  
3       -0.313112  
4       -0.313112

In [11]:
#with test data
scaler_mode = preprocessing.StandardScaler().fit(x_df_test)
scaled_x_df_test = scaler_mode.transform(x_df_test)
scaled_x_df_test = pd.DataFrame(scaled_x_df_test, columns=x_df_test.columns)

In [12]:
scaled_x_df_test.head()

temp  day_of_week_Friday  day_of_week_Monday  day_of_week_Saturday  \
0  0.449319           -0.369274           -0.436436             -0.436436   
1 -0.613260           -0.369274           -0.436436              2.291288   
2  1.056507           -0.369274            2.291288             -0.436436   
3 -0.916854           -0.369274           -0.436436             -0.436436   
4  0.449319           -0.369274           -0.436436             -0.436436   

   day_of_week_Sunday  day_of_week_Thursday  day_of_week_Tuesday  \
0           -0.294884                   0.0            -0.685994   
1           -0.294884                   0.0            -0.685994   
2           -0.294884                   0.0            -0.685994   
3           -0.294884                   0.0             1.457738   
4            3.391165                   0.0            -0.685994   

   day_of_week_Wednesday  month_APR  month_AUG  month_JUL  month_JUN  \
0               2.291288  -0.369274   2.708013  -0.623610  -0.436436   
1              -0.436436  -0.369274  -0.369274  -0.623610   2.291288   
2              -0.436436  -0.369274   2.708013  -0.623610  -0.436436   
3              -0.436436  -0.369274  -0.369274  -0.623610   2.291288   
4              -0.436436  -0.369274  -0.369274   1.603567  -0.436436   

   month_MAY  month_OCT  month_SEP  skies_Clear   skies_Cloudy  bobblehead_NO  \
0       -0.5  -0.294884  -0.204124      0.685994     -0.685994       0.561951   
1       -0.5  -0.294884  -0.204124      0.685994     -0.685994       0.561951   
2       -0.5  -0.294884  -0.204124      0.685994     -0.685994       0.561951   
3       -0.5  -0.294884  -0.204124     -1.457738      1.457738      -1.779513   
4       -0.5  -0.294884  -0.204124      0.685994     -0.685994      -1.779513   

   bobblehead_YES  
0       -0.561951  
1       -0.561951  
2       -0.561951  
3        1.779513  
4        1.779513

### 4) Ridge(L2) Regression with leave one out cross validation

In [13]:
l2_model = RidgeCV(alphas=np.linspace(0.1,1000,100), cv=None, store_cv_values=True)
l2_model.fit(scaled_x_df_train, y_df_train)

RidgeCV(alphas=array([1.000e-01, 1.020e+01, 2.030e+01, 3.040e+01, 4.050e+01, 5.060e+01,
       6.070e+01, 7.080e+01, 8.090e+01, 9.100e+01, 1.011e+02, 1.112e+02,
       1.213e+02, 1.314e+02, 1.415e+02, 1.516e+02, 1.617e+02, 1.718e+02,
       1.819e+02, 1.920e+02, 2.021e+02, 2.122e+02, 2.223e+02, 2.324e+02,
       2.425e+02, 2.526e+02, 2.627e+02, 2.728e+02, 2.829e+02, 2.930e+02,
       3.031e+02, 3.132e+02, 3.233e+0...
       7.273e+02, 7.374e+02, 7.475e+02, 7.576e+02, 7.677e+02, 7.778e+02,
       7.879e+02, 7.980e+02, 8.081e+02, 8.182e+02, 8.283e+02, 8.384e+02,
       8.485e+02, 8.586e+02, 8.687e+02, 8.788e+02, 8.889e+02, 8.990e+02,
       9.091e+02, 9.192e+02, 9.293e+02, 9.394e+02, 9.495e+02, 9.596e+02,
       9.697e+02, 9.798e+02, 9.899e+02, 1.000e+03]),
        cv=None, fit_intercept=True, gcv_mode=None, normalize=False,
        scoring=None, store_cv_values=True)

### Q2. Best L2 regularization coefficient and its corresponding linear coefficients.

In [14]:
print('alpha = ', l2_model.alpha_) 
print('coef = ', l2_model.coef_)
l2_predict = l2_model.predict(scaled_x_df_test)
print('R2= ',r2_score(y_df_test,l2_predict))

alpha =  50.6
coef =  [[  515.85380007    67.69322043  -835.67182144   490.25315842
    238.14165655  -341.53918562  1070.28517076  -617.19884398
   -273.56102806   457.54654532  -216.88248689  1102.57100111
   -605.71237164   -75.78927596  -186.41964828   271.19412682
   -271.19412682 -1145.58152754  1145.58152754]]
R2=  0.10450004637534283


### L1 Regularization

In [15]:
l1_model = LassoCV(alphas=np.linspace(0.1,1000,100), cv=scaled_x_df_train.shape[0])
l1_model.fit(scaled_x_df_train, y_df_train)

LassoCV(alphas=array([1.000e-01, 1.020e+01, 2.030e+01, 3.040e+01, 4.050e+01, 5.060e+01,
       6.070e+01, 7.080e+01, 8.090e+01, 9.100e+01, 1.011e+02, 1.112e+02,
       1.213e+02, 1.314e+02, 1.415e+02, 1.516e+02, 1.617e+02, 1.718e+02,
       1.819e+02, 1.920e+02, 2.021e+02, 2.122e+02, 2.223e+02, 2.324e+02,
       2.425e+02, 2.526e+02, 2.627e+02, 2.728e+02, 2.829e+02, 2.930e+02,
       3.031e+02, 3.132e+02, 3.233e+0...
       8.485e+02, 8.586e+02, 8.687e+02, 8.788e+02, 8.889e+02, 8.990e+02,
       9.091e+02, 9.192e+02, 9.293e+02, 9.394e+02, 9.495e+02, 9.596e+02,
       9.697e+02, 9.798e+02, 9.899e+02, 1.000e+03]),
        copy_X=True, cv=56, eps=0.001, fit_intercept=True, max_iter=1000,
        n_alphas=100, n_jobs=None, normalize=False, positive=False,
        precompute='auto', random_state=None, selection='cyclic', tol=0.0001,
        verbose=False)

### Q3. Best L1 regularization coefficient and its corresponding linear coefficients.

In [16]:
print('alpha = ', l1_model.alpha_)
print('coef = ', l1_model.coef_)
print('R2 = ', l1_model.score(scaled_x_df_test, y_df_test))

alpha =  484.9
coef =  [ 8.22025188e+02  0.00000000e+00 -1.16696636e+03  1.74176903e+02
  0.00000000e+00 -4.80145275e+02  1.38225666e+03 -8.85411307e+02
 -0.00000000e+00  7.53520951e+02  0.00000000e+00  1.93339335e+03
 -1.24766089e+02 -0.00000000e+00 -0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -2.64059882e+03  3.24819536e-13]
R2 =  0.07724321569205606


#### Linear Regression

In [17]:
linear_model = LinearRegression() 
linear_model.fit(scaled_x_df_train, y_df_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

### Q4.What are the predictive attributes selected as a result of L1 regularization?
#### Ans: The coefficients which are non zero contributes for the prediction. So, all the attributes with nen-zero coefficients are selected as predictive attributes. 
* temp
* day_of_week_Monday
* day_of_week_Saturday
* day_of_week_Thursday
* day_of_week_Tuesday
* day_of_week_Wednesday
* month_AUG
* month_JUN
* month_MAY
* bobblehead_NO
* bobblehead_YES


#### Go through the below code for clear understanding

In [18]:
x_df_train.columns
for i, attr in zip(range(len(x_df_train.columns)),l1_model.coef_):
    if attr!=0:
        print (x_df_train.columns[i])

temp
day_of_week_Monday
day_of_week_Saturday
day_of_week_Thursday
day_of_week_Tuesday
day_of_week_Wednesday
month_AUG
month_JUN
month_MAY
bobblehead_NO
bobblehead_YES


### Q5. For the models corresponding to the best L2 and L1 regularization coefficients list the following root-mean-square-error (RMSE): (1) RMSE on the training set, (2) expected prediction RMSE obtained during the cross-validation, (3) RMSE on the testing set. For the linear model without regularization list the following RMSE: (1) RMSE on the training set, and (2) RMSE on the testing set.

In [19]:
# check RMSE performance both training and testing for both L2 and L1 and no regularization and during cross validation.

# RMSE on training and test data of L2
l2_train_predict = l2_model.predict(scaled_x_df_train)
print('1. L2 - RMSE train = ', np.sqrt(mean_squared_error(l2_train_predict,y_df_train)))

l2_test_predict = l2_model.predict(scaled_x_df_test)
print('2. L2 - RMSE test = ', np.sqrt(mean_squared_error(l2_test_predict,y_df_test)))

# RMSE on training and test data of L1
l1_train_predict = l1_model.predict(scaled_x_df_train)
print('3. L1 - RMSE train = ', np.sqrt(mean_squared_error(l1_train_predict,y_df_train)))

l1_test_predict = l1_model.predict(scaled_x_df_test)
print('4. L1 - RMSE test = ', np.sqrt(mean_squared_error(l1_test_predict,y_df_test)))

# RMSE on training and test data of linear model without regularization

linear_train_predict = linear_model.predict(scaled_x_df_train)
print('5. No regularization - RMSE train = ', np.sqrt(mean_squared_error(linear_train_predict,y_df_train)))

linear_test_predict = linear_model.predict(scaled_x_df_test)
print('6. No regularization - RMSE test = ', np.sqrt(mean_squared_error(linear_test_predict,y_df_test)))

#Expected Prediction RMSE obtained during the cross validation for L2 and L1 Regularization
print("7. L2 Expected RMSE during cross validation = ", np.min(np.sqrt(l2_model.cv_values_.mean(axis = 0))))
print("8. L1 Expected RMSE during cross validation = ", np.min(np.sqrt(l1_model.mse_path_.mean(axis = 1))))


1. L2 - RMSE train =  5648.864216385293
2. L2 - RMSE test =  7797.67936197997
3. L1 - RMSE train =  5464.526854404769
4. L1 - RMSE test =  7915.460987936537
5. No regularization - RMSE train =  5254.5387249249425
6. No regularization - RMSE test =  7660.824357772815
7. L2 Expected RMSE during cross validation =  6737.660948839507
8. L1 Expected RMSE during cross validation =  7018.958314999469


### Q6. What observations can you make based on the above RMSE?
#### Ans: 
* Over Fitting on L1 and L2.

* L1 is performed better comparatively to that of L2 on test data

* Test RMSE is less than that of train RMSE in all three models 


### Q7. Predict the attendance on a clear Monday in June when the expected temperature is 72 for all three models with and without bobbleheads. Does bobblehead promotion have an impact on the attendance?7

In [20]:
bobblehead_no = x_df_train[x_df_train['month_JUN']==1]
bobblehead_no = bobblehead_no[bobblehead_no['day_of_week_Monday']==1]
bobblehead_no['temp']=72
bobblehead_no_scaled=scaler_mode.transform(bobblehead_no)

In [21]:
bobblehead_no_predict = l1_model.predict(bobblehead_no_scaled)
bobblehead_no_predict

array([39078.34364866])

In [22]:
bobblehead_no_predict = l2_model.predict(bobblehead_no_scaled)
bobblehead_no_predict

array([[39014.30636444]])

In [23]:
bobblehead_no_predict = linear_model.predict(bobblehead_no_scaled)
bobblehead_no_predict

array([[38583.55528661]])

In [24]:
bobblehead_no

temp  day_of_week_Friday  day_of_week_Monday  day_of_week_Saturday  \
17    72                   0                   1                     0   

    day_of_week_Sunday  day_of_week_Thursday  day_of_week_Tuesday  \
17                   0                     0                    0   

    day_of_week_Wednesday  month_APR  month_AUG  month_JUL  month_JUN  \
17                      0          0          0          0          1   

    month_MAY  month_OCT  month_SEP  skies_Clear   skies_Cloudy  \
17          0          0          0             1             0   

    bobblehead_NO  bobblehead_YES  
17              1               0

In [25]:
bobblehead_yes = bobblehead_no.copy()
bobblehead_yes['bobblehead_NO']=0
bobblehead_yes['bobblehead_YES']=1
bobblehead_yes

temp  day_of_week_Friday  day_of_week_Monday  day_of_week_Saturday  \
17    72                   0                   1                     0   

    day_of_week_Sunday  day_of_week_Thursday  day_of_week_Tuesday  \
17                   0                     0                    0   

    day_of_week_Wednesday  month_APR  month_AUG  month_JUL  month_JUN  \
17                      0          0          0          0          1   

    month_MAY  month_OCT  month_SEP  skies_Clear   skies_Cloudy  \
17          0          0          0             1             0   

    bobblehead_NO  bobblehead_YES  
17              0               1

In [26]:
bobblehead_yes_scaled=scaler_mode.transform(bobblehead_yes)

In [27]:
bobblehead_yes_predict = l1_model.predict(bobblehead_yes_scaled)
bobblehead_yes_predict

array([45261.21210986])

In [28]:
bobblehead_yes_predict = l2_model.predict(bobblehead_yes_scaled)
bobblehead_yes_predict

array([[44378.98338796]])

In [29]:
bobblehead_yes_predict = linear_model.predict(bobblehead_yes_scaled)
bobblehead_yes_predict

array([[45167.98210513]])

#### We can see that bobblehead promotion has effect on attendance and it's high in all three methods for bobblehead_YES